TARGET=mean foreach count1 find swap generate replace remove uniq reverse rotate perm part sort heap merge setalgo inplacemerge accum partialsum prio
CPPFLAGS=-g1 -I. -I..

all : $(TARGET)

clean :
	rm -f $(TARGET)
