TARGETS=test map1 settest algo1 copy3 reverseiter remove remove1 func funobj lambda bind2 cnttest vtest dtest ltest stest mtest1 sort1 mtest mmap1 mapcmp carray refsem1 ait

CPPFLAGS=-g -I. -std=c++0x

all : ${TARGETS}

clean :
	rm -f $(TARGETS)

